# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [89]:

# your code here
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder


df = pd.read_csv("/content/tic-tac-toe.csv")


label_encoder = LabelEncoder()
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = label_encoder.fit_transform(df[col])


X = df.drop(columns=["class"])
y = df["class"]


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [90]:
# your code here
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


model = Sequential([
    Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(8, activation='relu'),
    Dense(2, activation='softmax')
])


model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


model.fit(X_train, y_train, epochs=50, batch_size=8, validation_data=(X_test, y_test))





Epoch 1/50


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


96/96 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.5613 - loss: 0.7034 - val_accuracy: 0.6198 - val_loss: 0.6576
Epoch 2/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6507 - loss: 0.6425 - val_accuracy: 0.6510 - val_loss: 0.6402
Epoch 3/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6543 - loss: 0.6403 - val_accuracy: 0.6615 - val_loss: 0.6258
Epoch 4/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6505 - loss: 0.5972 - val_accuracy: 0.6823 - val_loss: 0.6159
Epoch 5/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6715 - loss: 0.5983 - val_accuracy: 0.6927 - val_loss: 0.6085
Epoch 6/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7077 - loss: 0.5765 - val_accuracy: 0.6927 - val_loss: 0.6001
Epoch 7/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7243 - loss: 0.5518 - val_accuracy: 0.7083 - val_loss: 0.5906
Epoch 8/50
96/96 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7334 - loss: 0.5522 - val_accuracy: 0.6979 - val_loss: 0.5813
Epo

In [91]:
test_loss, test_accuracy = model.evaluate(X_test, y_test)
print(f"Test accuracy: {test_accuracy:.4f}")


6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8454 - loss: 0.3692  
Test accuracy: 0.8542


In [92]:
model.export("tic-tac-toe.model")

model.save("tic-tac-toe.keras")
model.save("tic-tac-toe.h5")

Saved artifact at 'tic-tac-toe.model'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 9), dtype=tf.float32, name='keras_tensor_202')
Output Type:
  TensorSpec(shape=(None, 2), dtype=tf.float32, name=None)
Captures:
  136467115848720: TensorSpec(shape=(), dtype=tf.resource, name=None)
  136467115839696: TensorSpec(shape=(), dtype=tf.resource, name=None)
  136467115849680: TensorSpec(shape=(), dtype=tf.resource, name=None)
  136466868738896: TensorSpec(shape=(), dtype=tf.resource, name=None)
  136466868741008: TensorSpec(shape=(), dtype=tf.resource, name=None)
  136466868737168: TensorSpec(shape=(), dtype=tf.resource, name=None)


## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [93]:
# your code here

model = tf.keras.models.load_model("/content/tic-tac-toe.h5")


indices = np.random.choice(len(X_test), 5, replace=False)
X_sample = X_test[indices]
y_sample = y_test.iloc[indices]


predictions = model.predict(X_sample)


for i in range(len(X_sample)):
    print(f"Actual: {y_sample.iloc[i]}, Predicted: {np.argmax(predictions[i])}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step
Actual: True, Predicted: 1
Actual: True, Predicted: 1
Actual: False, Predicted: 0
Actual: True, Predicted: 1
Actual: False, Predicted: 0


## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [94]:
# your code here
import tensorflow as tf
from tensorflow.keras import layers, models

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.utils import to_categorical

df = pd.read_csv("tic-tac-toe.csv")

label_encoder = LabelEncoder()
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = label_encoder.fit_transform(df[col])



In [95]:
X = df.drop(columns=["class"])
y = df["class"]

y = to_categorical(y, num_classes=3)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)



In [96]:

def build_model(input_shape):
    model = models.Sequential([
        layers.Dense(64, activation='relu', input_shape=(input_shape,)),
        layers.Dense(64, activation='relu'),
        layers.Dense(3, activation='softmax')
    ])
    return model


optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)


input_shape = X_train.shape[1]
model = build_model(input_shape)
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])


history = model.fit(
    X_train, y_train,
    epochs=50,
    batch_size=32,
    validation_data=(X_test, y_test)
)



Epoch 1/50


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


24/24 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - accuracy: 0.6137 - loss: 0.8815 - val_accuracy: 0.6615 - val_loss: 0.6877
Epoch 2/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6727 - loss: 0.6359 - val_accuracy: 0.6719 - val_loss: 0.6216
Epoch 3/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7296 - loss: 0.5803 - val_accuracy: 0.6875 - val_loss: 0.5961
Epoch 4/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7295 - loss: 0.5551 - val_accuracy: 0.7083 - val_loss: 0.5696
Epoch 5/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7792 - loss: 0.5034 - val_accuracy: 0.7344 - val_loss: 0.5518
Epoch 6/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7772 - loss: 0.5067 - val_accuracy: 0.7396 - val_loss: 0.5299
Epoch 7/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4660 - val_accuracy: 0.7865 - val_loss: 0.5085
Epoch 8/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8262 - loss: 0.4564 - val_accuracy: 0.7865 - val_loss: 0.4879
Ep

In [97]:

loss, accuracy = model.evaluate(X_test, y_test)
print(f'Loss: {loss}, Accuracy: {accuracy}')


model.save('improved_model.h5')



6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9394 - loss: 0.1572 


Loss: 0.16381528973579407, Accuracy: 0.9427083134651184


In [98]:

loaded_model = tf.keras.models.load_model('improved_model.h5')


predictions = loaded_model.predict(X_test)
print(predictions)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step 
[[5.63832104e-01 4.36098516e-01 6.94388873e-05]
 [7.16783330e-02 9.28320229e-01 1.46971604e-06]
 [4.17251550e-02 9.58272219e-01 2.71063732e-06]
 [7.55163789e-01 2.44726539e-01 1.09688895e-04]
 [9.99999821e-01 6.83631214e-08 2.94255442e-09]
 [9.59965214e-03 9.90389705e-01 1.06749294e-05]
 [1.36526884e-03 9.98633087e-01 1.67120766e-06]
 [1.52220190e-01 8.47715735e-01 6.39496502e-05]
 [7.85171628e-01 2.14705646e-01 1.22668309e-04]
 [8.59318793e-01 1.40680507e-01 6.90901516e-07]
 [5.94202578e-02 9.40562546e-01 1.72712607e-05]
 [5.42140985e-03 9.94576693e-01 1.89152070e-06]
 [5.47839329e-04 9.99451995e-01 2.89197260e-07]
 [9.96123970e-01 3.87326023e-03 2.74721151e-06]
 [4.31800112e-02 9.56817210e-01 2.73587216e-06]
 [2.67862286e-02 9.73209262e-01 4.43667795e-06]
 [5.98074272e-02 9.40190554e-01 2.05452261e-06]
 [1.26484176e-02 9.87350881e-01 6.72520912e-07]
 [9.93352890e-01 6.64474396e-03 2.38348389e-06]
 [6.08733535e-01 3.91263932e-01 2.57812599e-06]
 [

**Which approach(es) did you find helpful to improve your model performance?**

In [99]:
# your answer here
# More layers enhanced the model's performance will increasing the number of epochs allowed the model to learn more effectively,
# Incorporating dropout layers also contributed to reducing overfitting, which improved generalization on the test dataset.